# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tekked Out Reality
email: me@tekkedout.net
description: > # this means to ignore newlines until "baseurl:"
  Greatful Software Developer who's living the dream, one day at a time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.tekkedout.net" # the base hostname & protocol for your site
twitter_username: TekHudson
github_username:  TekHudson
linkedin_username:  TekHudson

# Build settings
markdown: kramdown

